version: '3.8'
services:
  database:
    container_name: sc_database_container
    image: postgres:16
    env_file:
      - environments/prod/.env.postgres.prod
    volumes:
      - scatters-club-db-data:/var/lib/postgresql/data
      - ./directus/backups:/backups
    ports:
      - 5433:5432
    networks:
      # - scatters-club-net
      - scatters-club-reverse-proxy-net
    command: postgres -c shared_preload_libraries=pg_stat_statements -c log_statement=all -c log_min_messages=INFO

  directus:
    container_name: sc_directus_container
    image: directus/directus:10.7
    depends_on:
      - database
    env_file:
      - environments/prod/.env.directus.prod
    volumes:
      # - ./database:/directus/database:rw
      # - ./uploads:/directus/uploads:rw
      - ./directus/data/config:/var/directus/config
      - ./directus/data/uploads:/var/directus/public/uploads
      - ./directus/snapshots:/directus/snapshots
      - ./docker-configs/directus/gcp.json:/directus/gcp.json
    ports:
      - 8001:8055
    networks:
      # - scatters-club-net
      - scatters-club-reverse-proxy-net

  frontend:
    container_name: sc_frontend_container
    build:
      context: .
      dockerfile: docker-configs/frontend/Dockerfile
      target: production
    restart: always
    env_file:
      - environments/prod/.env.frontend.prod
    networks:
      # - scatters-club-net
      - scatters-club-reverse-proxy-net

  nginx:
    container_name: sc_nginx_container
    depends_on:
      - frontend
    restart: always
    build:
      context: ./docker-configs/nginx/prod
      dockerfile: prod.Dockerfile
    ports:
      - 3050:80
    links:
      - frontend
    networks:
      # - scatters-club-net
      - scatters-club-reverse-proxy-net

volumes:
  scatters-club-db-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  # scatters-club-net:
  #   driver: bridge
  scatters-club-reverse-proxy-net:
    external: true
