version: '3.8'
services:
  database:
    container_name: sc_database_container
    image: postgres:16
    env_file:
      - envs/dev/.env.postgres.dev
    volumes:
      - scatters-club-db-data:/var/lib/postgresql/data
      - ./directus/backups:/backups
    ports:
      - 5433:5432
    networks:
      # - scatters-club-net
      - scatters-club-reverse-proxy-net
    command: postgres -c shared_preload_libraries=pg_stat_statements -c log_statement=all -c log_min_messages=INFO

  pgadmin:
    container_name: sc_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - database
    env_file:
      - envs/dev/.env.pgadmin.dev
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      # - scatters-club-net
      - scatters-club-reverse-proxy-net

  directus:
    container_name: sc_directus_container
    image: directus/directus:10.7
    depends_on:
      - database
    env_file:
      - envs/dev/.env.directus.dev
    volumes:
      # - ./database:/directus/database:rw
      # - ./uploads:/directus/uploads:rw
      - ./directus/data/config:/var/directus/config
      - ./directus/data/uploads:/var/directus/public/uploads
      - ./directus/snapshots:/directus/snapshots
      - ./docker-configs/directus/gcp.json:/directus/gcp.json
    ports:
      - 8001:8055
    networks:
      # - scatters-club-net
      - scatters-club-reverse-proxy-net

  frontend:
    container_name: sc_frontend_container
    build:
      context: .
      dockerfile: docker-configs/frontend/Dockerfile
      target: development
    command: pnpm run dev
    restart: always
    env_file:
      - envs/dev/.env.frontend.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      # - scatters-club-net
      - scatters-club-reverse-proxy-net

  nginx:
    container_name: sc_nginx_container
    depends_on:
      - frontend
    restart: always
    build:
      context: ./docker-configs/nginx/
      dockerfile: dev.Dockerfile
    ports:
      - 3050:80
    links:
      - frontend
    networks:
      # - scatters-club-net
      - scatters-club-reverse-proxy-net

volumes:
  scatters-club-db-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  # scatters-club-net:
  #   driver: bridge
  scatters-club-reverse-proxy-net:
    external: true
